apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: muco
  labels:
    node: mucobaba
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: muco-app
        image: steelarch/node-app:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
