apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  namespace: muco
  labels:
    node: mucobaba 
spec:
  selector:
    app: node-app
  ports:
  - port: 80
    targetPort: 3000
